import Head from 'next/head'
import { Col, Container, Row, Spinner } from 'react-bootstrap'
import HeaderPokedex from '@/components/header'
import PokemonsCard from '@/components/pokemonCard'
import axios from 'axios'
import { useQuery } from 'react-query'

interface pokemonsData {
  count: number
  next: string
  previous: string
  results: Iresults[]
}
interface Iresults {

  name: string
  url: string

}
export default function Home() {

  const { data, isLoading } = useQuery('pokemons', () => {
    return axios.get('https://pokeapi.co/api/v2/pokemon?offset=0&limit=649')
      .then((response) => response.data)
  })

  if (isLoading) {
    return (
      <div className='loading' style={{
        backgroundColor: '#000000',
        height: ' 100vh',
        width: ' 100vw',
        display: ' flex',
        alignItems: ' center',
        justifyContent: ' center',
      }}
      >
        <Row>
          <Col xs='12' className='text-center'>
            <h2 className='text-danger'> Loading...</h2>
            <Spinner animation="border" variant="danger" />
          </Col>
        </Row>


      </div >
    )
  } else {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='content' >
          <HeaderPokedex />
          <Container className='py-5'>
            {isLoading ?
              <>carregandp</>
              :
              <Row>
                {data.results.map((pokemon: Iresults, index: number) => {
                  return (
                    <Col xs={12} md={6} lg={4} xl={3} key={index} className='px-4 py-5'>
                      <PokemonsCard
                        name={pokemon.name}
                        url={pokemon.url}
                        index={index}
                      />
                    </Col>
                  )
                })}
              </Row>
            }
          </Container>
        </div>
      </>
    )

  }

}
