import Head from 'next/head'
import { Button, Col, Container, Row, Spinner } from 'react-bootstrap'
import HeaderPokedex from '@/components/header'
import PokemonsCard from '@/components/pokemonCard'
import axios from 'axios'
import { Mutation, useMutation, useQuery } from 'react-query'
import { useEffect, useState } from 'react'

interface pokemonsData {
  count: number
  next: string
  previous: string
  results: Iresults[]
}
interface Iresults {

  name: string
  url: string

}
export default function Home() {
  const [searchType, setSearchType] = useState<string>('all')
  const [dataNameFiltred, setDataNameFiltred] = useState<string>('')
  const [quantityPage, setQuantityPage] = useState(20)

  const { data, isLoading, refetch } = useQuery(['pokemons', searchType], ({ queryKey }) => {
    return axios.get(`https://pokeapi.co/api/v2/pokemon?limit=${quantityPage}&offset=0`)
      .then((response) => response.data)
  })

  useEffect(() => {
    refetch()
  }, [quantityPage])

  if (isLoading) {
    return (
      <div className='loading' style={{
        backgroundColor: '#000000',
        height: ' 100vh',
        width: ' 100vw',
        display: ' flex',
        alignItems: ' center',
        justifyContent: ' center',
      }}
      >
        <Row>
          <Col xs='12' className='text-center'>
            <h2 className='text-danger'> Loading...</h2>
            <Spinner animation="border" variant="danger" />
          </Col>
        </Row>
      </div >
    )
  } else {
    return (
      <>
        <Head>
          <title>Minha pokedex</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='content' >
          <Container className='py-5'>

            <HeaderPokedex
              setSearchType={setSearchType}
              searchType={searchType}
              setDataNameFiltred={setDataNameFiltred}
            />
            <Button variant='dark' className='mt-3' onClick={() => setQuantityPage(quantityPage + 629)}>mostrar todos</Button>

            {isLoading ?
              <>carregandp</>
              :
              <Row>
                {data.results.map((pokemon: Iresults, index: number) => {
                  const pokemonName = pokemon.name.toLowerCase();
                  const searchText = dataNameFiltred.toLowerCase();

                  if (searchText === '' || pokemonName.includes(searchText)) {
                    return (
                      <Col xs={12} md={6} lg={4} xl={3} key={index} className='px-4 py-5'>
                        <PokemonsCard
                          name={pokemon.name}
                          url={pokemon.url}
                          index={index}
                          searchType={searchType}
                        />
                      </Col>
                    );
                  } else {
                    return null;
                  }
                })}
              </Row>
            }
            <Button variant='dark' onClick={() => setQuantityPage(quantityPage + 20)}>ver mais</Button>
          </Container>
        </div>
      </>
    )

  }

}
